name: Build EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # exeを作るのでWindows環境を使う

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile main.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: merged-json-tool
          path: dist/main.exe
